# Site settings
title: Gordon Pritchard
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://resume.example.com" # the base hostname & protocol for your site
github_username: blueismyboy
linkedin_path: in/blueismyboy # your linkedin url, without the leading www.linkedin.com/
email: email@example.com
excerpt_separator: "<!-- more -->"

# Build settings
markdown: kramdown
